language: python
python:
   - "3.6"

#Install dependencies
install: 
   - pip install -r dependencies.txt
   - npm i --prefix dmsite/venv
#Run Tests
script:
   - npm run build --prefix dmsite/venv
   - python dmsite/venv/manage.py check 
